- name: 'type: bug'
  description: 'Bug'
  color: '3e63dd'
- name: 'type: documentation'
  description: 'Documentation'
  color: '3e63dd'
- name: 'type: feature'
  description: 'Feature'
  color: '3e63dd'
- name: 'type: maintenance'
  description: 'Maintenance'
  color: '3e63dd'
- name: 'type: question'
  description: 'Question'
  color: '3e63dd'

- name: 'framework: dioxus'
  description: 'Dioxus'
  color: 'd6409f'
- name: 'framework: leptos'
  description: 'Leptos'
  color: 'd6409f'
- name: 'framework: yew'
  color: 'd6409f'
  description: 'Yew'
