[package]
name = "lucide-yew"
description = "Yew port of Lucide."
homepage = "https://lucide.rustforweb.org/yew.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
yew.workspace = true

[features]
default = []
full = []
