[package]
name = "lucide-dioxus"
description = "Dioxus port of Lucide."
homepage = "https://lucide.rustforweb.org/frameworks/dioxus.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dioxus.workspace = true
