[package]
name = "lucide-leptos"
description = "Leptos port of Lucide."
homepage = "https://lucide.rustforweb.org/frameworks/leptos.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
