[package]
name = "scripts"
description = "Scripts for Rust Lucide."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
convert_case = "0.8.0"
env_logger = "0.11.5"
git2 = "0.20.0"
log.workspace = true
octocrab = "0.45.0"
prettyplease = "0.2.25"
proc-macro2 = "1.0.92"
quote = "1.0.37"
regex = "1.11.1"
roxmltree = "0.21.0"
semver = "1.0.26"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
syn = "2.0.89"
tempfile = "3.14.0"
tokio = { version = "1.37.0", features = ["full"] }
