name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@dde39f6537f31ed953352c64c48f104ec9dee399
        with:
            target: wasm32-unknown-unknown
