name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@bdaeb4edfd8df63355139e11a364fb3e6871dac2
        with:
            target: wasm32-unknown-unknown
