name: Labels

on:
    workflow_dispatch:

permissions:
    contents: read
    issues: write

jobs:
    labels:
        name: Labels
        uses: RustForWeb/.github/.github/workflows/labels.yml@373c25f8fd29e10c40f1343f13312f8be3514af0
