name: Labels

on:
    workflow_dispatch:

permissions:
    contents: read
    issues: write

jobs:
    labels:
        name: Labels
        uses: RustForWeb/.github/.github/workflows/labels.yml@dde39f6537f31ed953352c64c48f104ec9dee399
