name: Publish

on:
    release:
        types: [published]

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        name: Publish
        uses: RustForWeb/.github/.github/workflows/publish.yml@dde39f6537f31ed953352c64c48f104ec9dee399
        with:
            target: wasm32-unknown-unknown
