name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: RustForWeb/.github/.github/workflows/release.yml@dde39f6537f31ed953352c64c48f104ec9dee399
        with:
            bump: ${{ inputs.bump }}
            target: wasm32-unknown-unknown
